#!/bin/bash

cd /data/work/virtualenvs/magaz/
source bin/activate
cd /data/work/virtualenvs/magaz/src/
../bin/django-admin startproject "$1"
cd "$1"
python manage.py startapp "$2"
cd "$2"
mkdir -p templates/"$1"